[project]
name = "stock-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.5.5",
    "pandas>=3.0.3",
    "pyarrow>=25.0.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "ruff>=0.15.21",
    "ty>=0.0.59",
]

[dependency-groups]
forecasting = [
    "scikit-learn>=1.9.0",
]
misc = [
    "pyspark>=4.1.2",
    "marimo>=0.23.14",
    "yfinance>=1.5.1",
]
news-service = [
    "alpaca-py>=0.43.5",
    "kafka-python>=3.0.9",
]
